### PR TITLE
Handle draft PR

### PR DESCRIPTION
**Pull request by banyan**
@kyanny should we handle a [draft PR](https://help.github.com/en/articles/about-pull-requests#draft-pull-requests) too? What do you think? 

### After

image

### CODE REVIEW

**Comment by kyanny** [comment]
@banyan 
I didn't know about Draft PR feature. Thanks!

(When I looked at your PR first, I was wondering if this Chrome extension is no longer usable because GitHub made official feature. But I recalled that this Chrome extension provides different feature for different use-case 😅 )

**Comment by kyanny** [comment]
@banyan 
I published v2.3.0 (including your change) to Chrome Web Store as a draft.
Can you confirm if it works fine?
You can install draft version from this URL https://chrome.google.com/webstore/detail/plebohahijhmebohbcifnaccfkjdgppe/publish-delayed?utm_source=chrome-ntp-icon
Once you confirm it works fine, I will make it available for all users.

**Comment by banyan** [comment]
@kyanny 

Thanks! Confirmed it works well 👍

**Comment by kyanny** [comment]
👍 Published to all users.

**Pull request merged**
